version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=express-postgres-docker-compose
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - 5432:5432

  app:
    container_name: expres-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - db
