version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=express-postgres-docker-compose
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  data: